### ISSUE TITLE
Update npm repository with latest version

### ISSUE THREAD

**Issue by KayoticSully** [enzy/digitalocean-api#8]
I am working on more automated testing but do you know when you want to push the new code out to npm?

**Comment by KayoticSully** [comment]
Well I did organize the tests but really much more testing proves very difficult and not worth my time currently.  I might make test-cases as needed.

**Comment by enzy** [comment]
Tests: I don't know how to test simple wrapper like this in a time efficient way (to code it). Any ideas?

NPM: I would like to include JSDocs with 1.0 release. Currently looking to automate its generation and pushto gh-pages branch (#7).
